### ISSUE TITLE
Insufficient number of input parameters. Error rbf (line 71) net.nout = nout;

### ISSUE THREAD

**Issue by Lygggggg** [rort1989/BH-HSMM#1]
Hello,i have some problems about the script 'script_data_synthesis_adversarial_complete_hdm_real_revised.m', When I execute this line of code ‘script_data_synthesis_evaluation’，The program reported the following error:
输入参数的数目不足。
出错 rbf (line 71)
net.nout = nout;
出错 btest (line 43)
            hh = hh + kernel(X(idx1), X(idx2));
出错 script_data_synthesis_evaluation (line 110)
        [~, p2,testStat(i,2)] = btest(num2cell(X,2), num2cell(Y,2));
出错 script_data_synthesis_adversarial_complete_hdm_real_revised (line 82)
script_data_synthesis_evaluation;

**Comment by rort1989** [comment]
Hello, could you provide following information to help trouble-shoot?
1. What is the dimension of X, Y, and value of idx1, idx2 when you got this error? Notice the ```dbstop if error;``` defined [here](https://github.com/rort1989/BH-HSMM/blob/master/code/script_data_synthesis_adversarial_complete_hdm_real_revised.m#L2), whenever you got an error in executing the 'script_data_synthesis_adversarial_complete_hdm_real_revised.m', Matlab will stop at the point triggers error, so you can check the values of parameters in workspace. 
2. What dataset were you using when get this error? Determined [here](https://github.com/rort1989/BH-HSMM/blob/master/code/script_data_synthesis_adversarial_complete_hdm_real_revised.m#L18)
3. Do you make any changes to the dataset configuration? Determined [here](https://github.com/rort1989/BH-HSMM/blob/master/code/script_data_synthesis_adversarial_complete_hdm_real_revised.m#L39-L43)

**Comment by Lygggggg** [comment]
Thank you for your reply, I have solved the previous problem. The reason is that the path /tools/bnt/netlab3.3 and the path tools/mmd_btest have the same function name-rbf.m, and an error occurs during the program running.
